allowBuilds:
  better-sqlite3: true
  core-js-pure: true
  dtrace-provider: true
  esbuild: true
  lefthook: true
  protobufjs: true
  re2: true
  sharp: true
  unrs-resolver: true
engineStrict: true
nodeVersion: 22.22.0
