name: lint / check

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup pnpm
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run secretlint
        shell: bash
        run: pnpm dlx @secretlint/quick-start $(git ls-files)
      - name: Run check
        run: pnpm check
      - name: Run lint
        run: |
          pnpm lint
          pnpm lint:renovate
